runSets = {    
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 0, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 10, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 50, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 6000, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 0, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 10, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 50, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 6000, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 0, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 10, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 50, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 6000, 'machinesNumber', 1, 'loadBalancer', 1, 'numClients', 5000), ...
 }


runSetsM3 = {    
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 0, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 10, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 50, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 6000, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 0, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 10, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 50, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 6000, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 0, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 10, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 50, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 6000, 'machinesNumber', 3, 'loadBalancer', 1, 'numClients', 5000), ...
 }  

runSetsM5 = {    
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 0, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 10, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 50, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 1, 'waitQueueLen', 6000, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 0, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 10, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 50, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 3, 'waitQueueLen', 6000, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 0, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 10, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 50, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
    struct('eventsGenerator', 1, 'lambda', 1, 'tmService', 2, 'nThreads', 5, 'waitQueueLen', 6000, 'machinesNumber', 5, 'loadBalancer', 1, 'numClients', 5000), ...
 }